spring:
  kafka:
    bootstrap-servers: localhost:9092 # Kafka ?? ??
    consumer:
      group-id: insurance-group # ??? ?? ID
  datasource:
    url: jdbc:h2:mem:testdb # H2 ?????? ?? URL
    driverClassName: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect # H2 ?????? dialect